services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Expose port 3000 on the host machine
    volumes:
      - ./frontend:/app  # Mount the current directory to the container for live reloading
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
